name: Run Cypress Test Cases

on:
  schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: "*/5 * * * *"
jobs:
  cypressTesting:
    name: Run Cypress Test Cases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Code 
      uses: actions/checkout@v4
      with:
        ref: test

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: NPM Install and start
      run: |
        yarn cache clean
        yarn install --network-concurrency 1
        nohup yarn start &

    # - name: Run ESLint and prettier
    #   run: |
    #     npm run lint

    - name: Cypress Install
      run: npx cypress install

    # - name: Cypress Run and Generate Report
    #   continue-on-error: true
    #   run: | 
    #     npx cypress run
      
    - name: Cypress run
      uses: cypress-io/github-action@v6
      continue-on-error: true
      env:
        # pass GitHub token to detect new build vs re-run build
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Copy test execution videos and screenshots
      continue-on-error: true
      run: |
        # mkdir public
        cp -r cypress/videos public/videos
        cp -r cypress/screenshots public/screenshots

    - name: Merge test reports
      run: npm run combine:report

    - name: Generate HTML report
      run: npm run generate:report
    
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: cypress-report-publish
        publish_dir: ./public

    - name: Send Discord Notification
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DISCORD_USERNAME: Cypress test Case Report
        DISCORD_EMBEDS: >
          {
            "embeds": [
              {
                "title": "Cypress Test Report Published!",
                "description": "The Cypress test report is now available.",
                "url": "https://pv-ani.github.io/sonarcloud-test/",
                "color": 5763719,
                "timestamp": "${{ github.event.created_at }}",
                "footer": {
                  "text": "Generated by GitHub Actions"
                }
              }
            ]
          }
      with:
        args: "Cypress test report is published: https://${{ github.repository }}/cypress-report-publish/"
