name: Run Cypress Test Cases

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: AWS Organization
        default: 'Select AWS Organization'
        options:
        - Select Organization
        - pv-tplus-beta
        - pv-tplus-prod
jobs:
  cypressTesting:
    name: Run Cypress Test Cases
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code 
      uses: actions/checkout@v4

    - name: Set node version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: NPM Install and start
      run: |
        yarn cache clean
        yarn install --network-concurrency 1
        nohup yarn start &

    - name: Run ESLint and prettier
      run: |
        npm run lint

    - name: Cypress Install
      run: npx cypress install

    - name: Cypress Run and Generate Report
      run: npx cypress run --reporter mochawesome
      
    # - name: Cypress run
    #   uses: cypress-io/github-action@v6
    #   with:
    #       record: true
    #   env:
    #     # pass GitHub token to detect new build vs re-run build
    #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Publish Test Report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: /home/runner/work/sonarcloud-test/sonarcloud-test/mochawesome-report/*.html
