# name: version test

# on:
#   push:
#     branches:
#     # - main
#     # - test

# jobs: 
#     upload-release:
#       runs-on: ubuntu-latest
#       steps:
#         - uses: actions/checkout@v4
  
#         - name: Set tag and release name
#           run: |
#             if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
#               echo "TAG_NAME=v${{ github.run_number }}.0.0" >> $GITHUB_ENV
#               echo "RELEASE_NAME=Release v${{ github.run_number }}.0.0" >> $GITHUB_ENV
#             elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
#               echo "TAG_NAME=v1.0.${{ github.run_number }}" >> $GITHUB_ENV
#               echo "RELEASE_NAME=Release v1.0.${{ github.run_number }}" >> $GITHUB_ENV
#             fi

#         - name: Create release
#           id: create_release
#           uses: actions/create-release@v1
#           env:
#             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           with:
#             tag_name: ${{ env.TAG_NAME }}
#             release_name: ${{ env.RELEASE_NAME }}
#             draft: false
#             prerelease: false
